In [1]:
import torch
import matplotlib.pyplot as plt

In [102]:
%run 'RG.py'

In [3]:
par = RGPartition([5,5])

In [4]:
par.mask

tensor([[False, False, False, False, False],
        [False,  True, False,  True, False],
        [False, False, False, False, False],
        [False,  True, False,  True, False],
        [False, False, False, False, False]])

In [7]:
par.mask.shape

torch.Size([5, 5])

In [105]:
rg = RGLayer([5,5],1)
x = torch.zeros(1,1,5,5)
rg.encode(x)

(tensor([[[[-0.0061, -0.0061],
           [-0.0061, -0.0061]]]], grad_fn=<ViewBackward0>),
 tensor([[[-0.5328, -0.0398, -0.5328, -0.0398, -0.5328, -0.4497, -0.4497,
           -0.4497, -0.5328, -0.0398, -0.5328, -0.0398, -0.5328, -0.4497,
           -0.4497, -0.4497, -0.5328, -0.0398, -0.5328, -0.0398, -0.5328]]],
        grad_fn=<IndexBackward0>))